Add Marketplace documentation
mautic/developer-documentation-new pull request #10
Opened 2021-11-14 15:59 UTC by dennisameling

Belongs to https://github.com/mautic/mautic/pull/10518

2021-11-15 11:00 UTC, RCheesley commented on docs/marketplace/listing.rst
> +- ``require.ext-*`` if your plugin require some PHP extension, please list them in the require section too. No one knows on what servers your plugin will run on.
```suggestion
- ``require.ext-*`` if your Plugin require some PHP extension, please list them in the require section too. As servers can have a wide variety of extensions enabled, this ensures that the correct extensions are available.
```

2021-11-15 11:01 UTC, RCheesley commented on docs/marketplace/listing.rst
> +- ``require.mautic/core-lib`` it's important to specify which Mautic versions your plugin supports. Include only the versions you or your community have tested and confirmed the plugin works with.
```suggestion
- ``require.mautic/core-lib`` it's important to specify which Mautic versions your Plugin supports. Include only the versions you or your community have tested and confirmed the Plugin works with.
```

2021-11-15 11:02 UTC, RCheesley commented on docs/marketplace/listing.rst
> +Step 2: check best practices
```suggestion
Step 2: verify best practices
```

2021-11-15 11:02 UTC, RCheesley commented on docs/marketplace/listing.rst
> +There's a few things we highly recommend when creating plugins for Mautic. Please refer to the :doc:`./best_practices` page for more details.
```suggestion
There's a few things which are highly recommend when creating Plugins for Mautic. Please refer to the :doc:`./best_practices` page for more details.
```

2021-11-15 11:03 UTC, RCheesley commented on docs/marketplace/listing.rst
> +When the composer.json is ready, follow the `Publishing Packages <https://packagist.org>`_ section directly in Packagist.
Please use the external linking extension here!

2021-11-15 11:09 UTC, RCheesley commented on docs/marketplace/listing.rst
> +While the Mautic Marketplace is still in beta, you'll have to apply for our allowlist in order to show up in the Marketplace. We expect to move to stable with Mautic 4.2 in February 2022, after which
```suggestion
While the Mautic Marketplace is still in beta, you'll have to apply for our allowlist in order to show up in the Marketplace. It is expected that the Marketplace will move from beta to stable release with Mautic 4.2 in February 2022, after which the allowlist may be deprecated in favour of a blocklist. Please refer to the :doc:`./allowlist_what_and_why` page for more details.
```

2021-11-15 11:11 UTC, RCheesley commented on docs/marketplace/listing.rst
> +Updating existing plugins for usage with the Marketplace
```suggestion
Updating existing Plugins for usage with the Marketplace
```

2021-11-15 11:12 UTC, RCheesley commented on docs/marketplace/listing.rst
> +Next to that, if you built your plugin for Mautic 3 originally, please check our `UPGRADE-4.0.md guide <https://github.com/mautic/mautic/blob/4.x/UPGRADE-4.0.md>`_ for the breaking changes we made in
```suggestion
Next to that, if you built your plugin for Mautic 3 originally, please check the `UPGRADE-4.0.md guide <https://github.com/mautic/mautic/blob/4.x/UPGRADE-4.0.md>`_ for the breaking changes in Mautic 4.
```

2021-11-15 11:16 UTC, RCheesley commented
@dennisameling should also mention that Vale seems to be passing despite an awful lot of warnings - is it configured correctly?

2021-11-21 12:51 UTC, dennisameling commented
@RCheesley 
- Added a build + checklinks step to CI - this ensures that external links can actually be reached (404/500/etc. error codes will fail the job)
- Added Vale + several plugins like GitLens to Gitpod, so that contributors see the warnings/suggestions right within their editor while working on docs
- Moved external links to their own files as requested
- Fixed several warnings & suggestions

There's two small TODOs left in this PR - adding screenshots and linking to the plugin creation docs (which I'll create in a separate PR)

2021-11-23 12:26 UTC, RCheesley requested changes
One small fix to grammar otherwise good to go. Let's not forget the TODOs!

Also as a side note, when I spun up Gitpod it asked me to install Python (the extension maybe?) and it says Vale is not available. Maybe something is not quite right there?

2021-11-23 12:26 UTC, RCheesley commented on docs/marketplace/allowlist_what_and_why.rst
> +Allowlist: what's it and why is it needed?
```suggestion
Allowlist: what is it and why is it needed?
```
Guessing this was a Vale correction but actually makes better grammatical sense to not abbreviate in that way.

2021-12-03 14:48 UTC, merged