Add more REST API docs
mautic/developer-documentation-new pull request #100
Opened 2022-12-07 01:11 UTC by dennisameling

Related to https://github.com/mautic/developer-documentation-new/issues/97

2022-12-07 01:57 UTC, dennisameling commented
@RCheesley here's another batch of REST API docs. I'm starting to get a bit short on time but will do everything I can to keep up the pace. If we can keep going at this speed, by the end of this week we'll be in a good enough position to "flip the switch" and launch the new docs 🔥 😮‍💨 Thanks for the quick reviews!

2022-12-07 15:45 UTC, RCheesley requested changes
Oooof, quite a big PR, thanks @dennisameling 🚀 

Quite a lot of suggestions but they are very similar in nature:

- Camel case / not camel case on headings
- Consistency with full stops at the end of the tabulated information (we seem to not use them, so I've removed them)
- Some suggestions for better phrasing for some of the field descriptions
- A couple of typos / incorrect text spotted
- Using more diverse names in code samples (figured we could update as we go, might as well do it now!)

Thanks again for all your time in getting this over to the new dev docs!

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/assets.rst
> +If ``PUT``\ , the expected response code is ``200`` if the Asset got edited or ``201`` if created.
```suggestion
If ``PUT``\ , the expected response code if editing the Asset is ``200`` or ``201`` if created.
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/assets.rst
> +If ``PATCH``\ , the expected response code is ``200``.
```suggestion
If using ``PATCH``\ , the expected response code is ``200``.
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/assets.rst
> +Delete asset
```suggestion
Delete Asset
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/campaigns.rst
> +   $apiUrl      = "https://your-mautic.com";
```suggestion
   $apiUrl      = "https://example.com";
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/campaigns.rst
> +Get campaign
```suggestion
Get Campaign
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/campaigns.rst
> +           "modifiedByUser": "Joe Smith",
```suggestion
           "modifiedByUser": "Iris Durand",
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/campaigns.rst
> +           "createdByUser": "Joe Smith",
```suggestion
           "createdByUser": "Delfina Henderson",
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/campaigns.rst
> +     - Date/time when the Campaign should get published
```suggestion
     - Campaign publish date/time
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/campaigns.rst
> +     - Date/time the Campaign should get unpublished
```suggestion
     - Campaign unpublish date/time
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/campaigns.rst
> +     - Date/time Campaign got created
```suggestion
     - Campaign creation date/time
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/campaigns.rst
> +     - Date/time Campaign was last modified
```suggestion
     - Campaign modified date/time
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/campaigns.rst
> +               "createdByUser": "Joe Smith",
```suggestion
               "createdByUser": "Lucine Van der Zee",
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/campaigns.rst
> +               "modifiedByUser": "Joe Smith",
```suggestion
               "modifiedByUser": "Lucine Van der Zee",
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/campaigns.rst
> +Create campaign
```suggestion
Create Campaign
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/campaigns.rst
> +Create a new Campaign. To see more advanced example with Campaign events and so on, see the unit tests.
```suggestion
Create a new Campaign. To see a more advanced example with Campaign events and so on, see the unit tests.
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/campaigns.rst
> +Clone a campaign
```suggestion
Clone a Campaign
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/campaigns.rst
> +Clone an existing Campaign. To see more advanced example with Campaign events and so on, see the unit tests.
```suggestion
Clone an existing Campaign. To see a more advanced example with Campaign events and so on, see the unit tests.
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/campaigns.rst
> +If ``PUT``, the expected response code is ``200`` if the Campaign got edited or ``201`` if created.
```suggestion
If using ``PUT``, the expected response code is ``200`` if editing the Campaign, or ``201`` if creating a Campaign.
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/campaigns.rst
> +If ``PATCH``, the expected response code is ``200``.
```suggestion
If using ``PATCH``, the expected response code is ``200``.
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/campaigns.rst
> +Delete campaign
```suggestion
Delete Campaign
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/campaigns.rst
> +Add contact to a campaign
```suggestion
Add Contact to a Campaign
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/campaigns.rst
> +Remove contact from a campaign
```suggestion
Remove Contact from a Campaign
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/categories.rst
> +Use this endpoint to obtain details on Mautic'sCategories or to manipulate Category memberships.
```suggestion
Use this endpoint to obtain details on Mautic's Categories, or to manipulate Category memberships.
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/categories.rst
> +**Category Properties**
```suggestion
**Category properties**
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/categories.rst
> +     - Date/time Category got created
```suggestion
     - Category creation date/time
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/categories.rst
> +List contact categories
```suggestion
List Contact Categories
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/categories.rst
> +Returns a list of ContactCategories available to the User. This list isn't filterable.
```suggestion
Returns a list of Contact Categories available to the User. This list isn't filterable.
```
I think this is correct but please check for technical accuracy.

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/categories.rst
> +Create category
```suggestion
Create Category
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/fields.rst
> +     - ``true`` if the field value can get changed from public requests. The tracking pixel query for example.
```suggestion
     - ``true`` if the field value can be changed from public requests - the tracking pixel query for example
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/fields.rst
> +List contact fields
```suggestion
List Contact fields
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/fields.rst
> +     - Date/time when the field should get published
```suggestion
     - Field publish date/time
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/fields.rst
> +     - Date/time the field should get unpublished
```suggestion
     - Field unpublish date/time
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/fields.rst
> +     - Date/time field got created
```suggestion
     - Field creation date/time
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/fields.rst
> +     - Which object use the field. Contact or Company.
```suggestion
     - Which object uses the field\ Contact or Company
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/fields.rst
> +     - Default value of the field.
```suggestion
     - Default value of the field
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/fields.rst
> +     - ``true`` if this is a required field.
```suggestion
     - ``true`` if this is a required field
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/fields.rst
> +     - ``true`` if the field value can get changed from public requests. The tracking pixel query for example.
```suggestion
     - ``true`` if the field value can be changed from public requests - the tracking pixel query for example
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/fields.rst
> +     - ``true`` if the field is unique identifier and so the Contacts should merge if the value of this field is the same.
```suggestion
     - ``true`` if the field is a unique identifier therefore Contacts should merge if the value of this field is the same
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/fields.rst
> +     - Field options if the field type needs some.
```suggestion
     - Field options if the field type needs some
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/fields.rst
> +**Multiselect Field**
```suggestion
**Multiselect field**
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/fields.rst
> +**POST Parameters**
```suggestion
**POST parameters**
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/fields.rst
> +     - ``true`` if the field value can get changed from public requests. The tracking pixel query for example.
```suggestion
     - ``true`` if the field value can be changed from public requests - the tracking pixel query for example
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/fields.rst
> +     - ``true`` if the field value can get changed from public requests. The tracking pixel query for example.
```suggestion
     - ``true`` if the field value can be changed from public requests - the tracking pixel query for example
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/fields.rst
> +     - Which object use the field. Contact or Company.
```suggestion
     - Which object uses the field, Contact or Company
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/fields.rst
> +     - Default value of the field.
```suggestion
     - Default value of the field
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/fields.rst
> +     - ``true`` if this is a required field.
```suggestion
     - ``true`` if this is a required field
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/fields.rst
> +     - ``true`` if the field is unique identifier and so the Contacts should merge if the value of this field is the same.
```suggestion
     - ``true`` if the field is a unique identifier and therefore Contacts should merge if the value of this field is the same
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/fields.rst
> +     - Field options if the field type needs some.
```suggestion
     - Field options if the field type needs some.
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/fields.rst
> +     - Which object use the field. Contact or Company.
```suggestion
     - Which object uses the field, Contact or Company
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/fields.rst
> +     - ``true`` if this is a required field.
```suggestion
     - ``true`` if this is a required field
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/fields.rst
> +     - ``true`` if the field is unique identifier and so the Contacts should merge if the value of this field is the same.
```suggestion
     - ``true`` if the field is unique identifier and so the Contacts should merge if the value of this field is the same
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/fields.rst
> +     - Field options if the field type needs some.
```suggestion
     - Field options if the field type needs some
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/assets.rst
> +     - Date/time Asset was last modified
```suggestion
     - Asset modified date/time
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/assets.rst
> +     - String or search command to filter entities by.
```suggestion
     - String or search command to filter entities by
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/assets.rst
> +     - Starting row for the entities returned. Defaults to 0.
```suggestion
     - Starting row for the entities returned, defaults to 0
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/assets.rst
> +     - Limit number of entities to return. Defaults to the system configuration for pagination, which defaults to 30.
```suggestion
     - Limit number of entities to return, defaults to the system configuration for pagination - default of 30
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/assets.rst
> +     - Column to sort by. Can use any column listed in the response.
```suggestion
     - Column to sort by, can use any column listed in the response
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/assets.rst
> +     - Sort direction: ``asc`` or ``desc``.
```suggestion
     - Sort direction: ``asc`` or ``desc``
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/assets.rst
> +     - Only return currently published entities.
```suggestion
     - Only return currently published entities
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/assets.rst
> +     - Return only array of entities without additional lists in it.
```suggestion
     - Return only array of entities without additional lists in it
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/assets.rst
> +     - Either URL for remote file or filename for local file.
```suggestion
     - Either URL for remote file or filename for local file
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/assets.rst
> +     - Either URL for remote file or filename for local file.
```suggestion
     - Either URL for remote file or filename for local file
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/campaigns.rst
> +     - Array of Event entities for the Campaign. See below.
```suggestion
     - Array of Event entities for the Campaign - see below
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/campaigns.rst
> +     - If the event connects to an action, this value is "no" for the non-decision path or "yes" for the actively followed path.
```suggestion
     - If the event connects to an action, this value is "no" for the non-decision path or "yes" for the actively followed path
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/campaigns.rst
> +List campaigns
```suggestion
List Campaigns
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/campaigns.rst
> +     - String or search command to filter entities by.
```suggestion
     - String or search command to filter entities by
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/campaigns.rst
> +     - Starting row for the entities returned. Defaults to 0.
```suggestion
     - Starting row for the entities returned, defaults to 0
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/campaigns.rst
> +     - Limit number of entities to return. Defaults to the system configuration for pagination, which defaults to 30.
```suggestion
     - Limit number of entities to return, defaults to the system configuration for pagination - default of 30
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/campaigns.rst
> +     - Column to sort by. Can use any column listed in the response.
```suggestion
     - Column to sort by, can use any column listed in the response
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/campaigns.rst
> +     - Sort direction: ``asc`` or ``desc``.
```suggestion
     - Sort direction: ``asc`` or ``desc``
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/campaigns.rst
> +     - Only return currently published entities.
```suggestion
     - Only return currently published entities
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/campaigns.rst
> +     - Return only array of entities without additional lists in it.
```suggestion
     - Return only array of entities without additional lists in it
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/categories.rst
> +   $apiUrl      = "https://your-mautic.com";
```suggestion
   $apiUrl      = "https://example.com";
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/fields.rst
> +.. vale off
```suggestion
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/fields.rst
> +.. vale on
```suggestion
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/fields.rst
> +     - String or search command to filter entities by.
```suggestion
     - String or search command to filter entities by
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/fields.rst
> +     - Starting row for the entities returned. Defaults to 0.
```suggestion
     - Starting row for the entities returned, defaults to 0
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/fields.rst
> +     - Limit number of entities to return. Defaults to the system configuration for pagination, which defaults to 30.
```suggestion
     - Limit number of entities to return, defaults to the system configuration for pagination - defaults to 30
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/fields.rst
> +     - Column to sort by. Can use any column listed in the response.
```suggestion
     - Column to sort by, can use any column listed in the response
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/fields.rst
> +     - Sort direction: ``asc`` or ``desc``.
```suggestion
     - Sort direction: ``asc`` or ``desc``
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/fields.rst
> +     - Only return currently published entities.
```suggestion
     - Only return currently published entities
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/fields.rst
> +     - Return only array of entities without additional lists in it.
```suggestion
     - Return only array of entities without additional lists in it
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/fields.rst
> +If ``PUT``, the expected response code is ``200`` if the field got edited or ``201`` if created.
```suggestion
If using ``PUT``, the expected response code is ``200`` if editing the field or ``201`` if creating the field.
```

2022-12-07 15:45 UTC, RCheesley commented on docs/rest_api/fields.rst
> +If ``PATCH``, the expected response code is ``200``.
```suggestion
If using ``PATCH``, the expected response code is ``200``.
```

2022-12-11 21:38 UTC, dennisameling commented
Thanks for the feedback and suggestions @RCheesley! I'll keep them in mind for the remainder of the REST API docs and the other sections! 🔥

2022-12-11 21:42 UTC, merged