Development environment
mautic/developer-documentation-new pull request #126
Opened 2023-04-27 17:47 UTC by lenonleite

We are opening a new Pull Request with documentation about installation and a new way to work with environments, following Symfony environments structures. 

=)

2023-05-03 08:03 UTC, RCheesley requested changes
Hey @lenonleite thanks so much for pushing this PR over to the docs!

I have made some suggestions as there were quite a few issues reported with Vale and the RST syntax. 

I have provided links to the reasons why the issues are being flagged up so that you can understand what they mean!

Also, please ensure that you commit the link files when you create them with the 'make link' command!

Ping me on Slack if you need any help with any of this! Happy to run through with you how to use Vale within VSCode as it really does help you to pick things up as you write!

2023-05-03 08:03 UTC, RCheesley commented on docs/development-environment/environments.rst
> +############################################################
This underline is far too long - it must be the length of the title only.

```suggestion
############
```

2023-05-04 10:43 UTC, lenonleite commented on docs/development-environment/environments.rst
> +==================
I didn't know, thank you, =)

2023-05-04 10:43 UTC, lenonleite commented on docs/development-environment/environments.rst
> +.. code-block:: env
Yeah, I will use bash, thank you =)

2023-05-04 13:09 UTC, lenonleite commented
@RCheesley , =)
First of all, thank you for explaining and for sending many details and links to learn. =)

And I finished the corrections based on the comments.

2023-05-04 14:20 UTC, RCheesley requested changes
Great work on this @lenonleite - just one bit where we need to remove the duplicate warning and space beneath and then good to go! 🚀 

Note: The build failure is due to existing issues which need to be corrected in a separate PR.

2023-05-04 14:20 UTC, RCheesley commented on docs/development-environment/environments.rst
> +.. warning:: All secrets should add via environment variables or through other secret management.
```suggestion
```

2023-05-06 00:00 UTC, lenonleite commented on docs/development-environment/environments.rst
> +.. warning:: All secrets should add via environment variables or through other secret management.
a bit later, but done.

=)

2023-07-24 09:06 UTC, RCheesley commented
PR is good to merge - the build warnings need to be addressed in a separate PR.

2023-07-24 09:06 UTC, merged