WIP The start of Webhook documentation
mautic/developer-documentation-new pull request #14
Opened 2021-11-18 00:11 UTC by alanhartless

2021-12-03 17:32 UTC, RCheesley requested changes
A few minor changes mostly to grammar :)

Thanks for writing this up, great job! 🚀

2021-12-03 17:32 UTC, RCheesley commented on docs/webhooks/events/lead_company_change.rst
> +Triggered when Mautic adds or removes a Company to/from a Company.
```suggestion
Triggered when Mautic adds or removes a Contact to/from a Company.
```

I think this should be when a contact is added/removed.

2021-12-03 17:32 UTC, RCheesley commented on docs/webhooks/events/lead_post_delete.rst
> +Triggered when Mautic deletes Contact.
```suggestion
Triggered when Mautic deletes a Contact.
```

2021-12-03 17:32 UTC, RCheesley commented on docs/webhooks/events/lead_post_save_new.rst
> +.. _Custom field properties:
```suggestion
.. _Custom Field properties:
```

I think both should be capitalised as it's the name of a feature of Mautic.

2021-12-03 17:32 UTC, RCheesley commented on docs/webhooks/events/lead_post_save_new.rst
> +Custom field properties
```suggestion
Custom Field properties
```

2021-12-03 17:32 UTC, RCheesley commented on docs/webhooks/events/lead_post_save_new.rst
> +      - ID of the channel subscription entry.
```suggestion
      - ID of the Channel subscription entry.
```

2021-12-03 17:32 UTC, RCheesley commented on docs/webhooks/events/lead_post_save_new.rst
> +      - ID of the specific channel entity the Contact clicked to unsubscribe from.
```suggestion
      - ID of the specific Channel entity the Contact clicked to unsubscribe from.
```

2021-12-03 17:32 UTC, RCheesley commented on docs/webhooks/getting_started.rst
> +Webhooks are a universal way how to send data about Contacts and their activity to a third party in either real-time, as the change/activity happens, or queued to be sent in batches through backgroun
```suggestion
Webhooks are a universal way to send data about Contacts and their activity to a third party in either real-time - as the change/activity happens - or queued - to be sent in batches through background cron jobs.
```

2021-12-03 17:32 UTC, RCheesley commented on docs/webhooks/getting_started.rst
> +The structure of Webhook payloads are like the following. ``WebhookEventType`` would be the event's actual type and `WebhookEventPayload` will contain the event's data.
```suggestion
The structure of Webhook payloads are as follows. ``WebhookEventType`` would be the event's actual type and `WebhookEventPayload` will contain the event's data.
```

2021-12-03 23:52 UTC, alanhartless commented
@dennisameling @RCheesley I think this is an example of where we may not want to convert Sphinx warnings into errors. 

This is failing to build because of 
```
Warning, treated as error:
/home/runner/work/developer-documentation-new/developer-documentation-new/docs/webhooks/events/company_post_save.rst:8:duplicate label event type, other instance in /home/runner/work/developer-documentation-new/developer-documentation-new/docs/webhooks/events/company_post_delete.rst
```
These were defined this way on purpose because I didn't want to uniquely name `Event type` and `Event properties` for every Webhook as they'll end up with really long titles for some to ensure unique across contact or company related ones. These are also defined as document paragraphs (`""""""""""""""""""`) which are converted to fragments instead of paths so I think this should really be considered a bug in the linter.

2021-12-17 16:02 UTC, RCheesley commented
If it's a bug in the linter, then we'd make an upstream issue report I guess to Vale?

If the error is something we can safely skip then let's get it merged.

2022-01-13 15:47 UTC, merged