Add more REST API docs (Dashboard Widget Data, Dynamic Content, Point Actions, Point Triggers, Webhooks)
mautic/developer-documentation-new pull request #144
Opened 2023-07-30 12:39 UTC by dennisameling

Almost there! Another bunch of REST API docs as mentioned in https://github.com/mautic/developer-documentation-new/issues/97

2023-07-30 12:41 UTC, dennisameling commented
The remaining Vale errors are a known issue with not being able to do `vale off` on headings: https://github.com/errata-ai/vale/issues/340#issuecomment-1339799018

2023-07-30 20:51 UTC, RCheesley requested changes
A few fairly small suggestions - thanks so much for porting this over @dennisameling 🚀

2023-07-30 20:51 UTC, RCheesley commented on docs/rest_api/dynamic_content.rst
> +Use this endpoint to obtain details on Mautic's web Dynamic Content.
```suggestion
Use this endpoint to obtain details on Mautic's Dynamic Web Content.
```

2023-07-30 20:51 UTC, RCheesley commented on docs/rest_api/dynamic_content.rst
> +Create a new dynamicContent.
```suggestion
Create a new Dynamic Content.
```
I _think_ these should be separate words unless it's purposely written as above in the code sample.

2023-07-30 20:51 UTC, RCheesley commented on docs/rest_api/dynamic_content.rst
> +Edit a new dynamicContent. Note that this supports PUT or PATCH depending on the desired behavior.
```suggestion
Edit a new Dynamic Content. Note that this supports PUT or PATCH depending on the desired behavior.
```
As above.

2023-07-30 20:51 UTC, RCheesley commented on docs/rest_api/dynamic_content.rst
> +**PUT** creates a dynamicContent if the given ID doesn't exist and clears all the Dynamic Content information, adds the information from the request.
```suggestion
**PUT** creates a Dynamic Content if the given ID doesn't exist and clears all the Dynamic Content information, adds the information from the request.
```

2023-07-30 20:51 UTC, RCheesley commented on docs/rest_api/dynamic_content.rst
> +To edit a dynamicContent and return a 404 if the Dynamic Content isn't found:
```suggestion
To edit a Dynamic Content and return a 404 if the Dynamic Content isn't found:
```

2023-07-30 20:51 UTC, RCheesley commented on docs/rest_api/dynamic_content.rst
> +To edit a dynamicContent and create a new one if the Dynamic Content isn't found:
```suggestion
To edit a Dynamic Content and create a new one if the Dynamic Content isn't found:
```

2023-07-30 20:51 UTC, RCheesley commented on docs/rest_api/dynamic_content.rst
> +Delete a dynamicContent.
```suggestion
Delete a Dynamic Content.
```

2023-07-30 20:51 UTC, RCheesley commented on docs/rest_api/point_actions.rst
> +     - ID of the point
```suggestion
     - ID of the Point Action
```

I think this should use the full term.

2023-07-30 20:51 UTC, RCheesley commented on docs/rest_api/point_actions.rst
> +     - Name of the point
```suggestion
     - Name of the Point Action
```

2023-07-30 20:51 UTC, RCheesley commented on docs/rest_api/point_actions.rst
> +     - Description of the point
```suggestion
     - Description of the Point Action
```

2023-07-30 20:51 UTC, RCheesley commented on docs/rest_api/point_actions.rst
> +     - Point publish date/time
```suggestion
     - Point Action publish date/time
```

2023-07-30 20:51 UTC, RCheesley commented on docs/rest_api/point_actions.rst
> +     - Point unpublish date/time
```suggestion
     - Point Action unpublish date/time
```

2023-07-30 20:51 UTC, RCheesley commented on docs/rest_api/point_actions.rst
> +     - Point creation date/time
```suggestion
     - Point Action creation date/time
```

2023-07-30 20:51 UTC, RCheesley commented on docs/rest_api/point_actions.rst
> +     - ID of the User that created the point
```suggestion
     - ID of the User that created the Point Action
```

2023-07-30 20:51 UTC, RCheesley commented on docs/rest_api/point_actions.rst
> +     - Name of the User that created the point
```suggestion
     - Name of the User that created the Point Action
```

2023-07-30 20:51 UTC, RCheesley commented on docs/rest_api/point_actions.rst
> +     - Date/time point was last modified
```suggestion
     - Date/time Point Action was last modified
```

2023-07-30 20:51 UTC, RCheesley commented on docs/rest_api/point_actions.rst
> +     - ID of the User that last modified the point
```suggestion
     - ID of the User that last modified the Point Action
```

2023-07-30 20:51 UTC, RCheesley commented on docs/rest_api/point_actions.rst
> +     - Name of the User that last modified the point
```suggestion
     - Name of the User that last modified the Point Action
```

2023-07-30 20:51 UTC, RCheesley commented on docs/rest_api/point_actions.rst
> +     - The number of Points to assign to the Contact when executing this action
```suggestion
     - The number of Points to assign to the Contact when executing this Point Action
```

2023-07-30 20:51 UTC, RCheesley commented on docs/rest_api/point_triggers.rst
> +     - ID of the point
```suggestion
     - ID of the Point Trigger
```

2023-07-30 20:51 UTC, RCheesley commented on docs/rest_api/point_triggers.rst
> +     - Name of the point
```suggestion
     - Name of the Point Trigger
```

2023-07-30 20:51 UTC, RCheesley commented on docs/rest_api/point_triggers.rst
> +     - Description of the point
```suggestion
     - Description of the Point Trigger
```

2023-07-30 20:51 UTC, RCheesley commented on docs/rest_api/point_triggers.rst
> +     - Point publish date/time
```suggestion
     - Point Trigger publish date/time
```

2023-07-30 20:51 UTC, RCheesley commented on docs/rest_api/point_triggers.rst
> +     - Point unpublish date/time
```suggestion
     - Point Trigger unpublish date/time
```

2023-07-30 20:51 UTC, RCheesley commented on docs/rest_api/point_triggers.rst
> +     - Point creation date/time
```suggestion
     - Point Trigger creation date/time
```

2023-07-30 20:51 UTC, RCheesley commented on docs/rest_api/point_triggers.rst
> +     - ID of the User that created the point
```suggestion
     - ID of the User that created the Point Trigger
```

2023-07-30 20:51 UTC, RCheesley commented on docs/rest_api/point_triggers.rst
> +     - Name of the User that created the point
```suggestion
     - Name of the User that created the Point Trigger
```

2023-07-30 20:51 UTC, RCheesley commented on docs/rest_api/point_triggers.rst
> +     - Date/time point was last modified
```suggestion
     - Date/time Point Trigger was last modified
```

2023-07-30 20:51 UTC, RCheesley commented on docs/rest_api/point_triggers.rst
> +     - ID of the User that last modified the point
```suggestion
     - ID of the User that last modified the Point Trigger
```

2023-07-30 20:51 UTC, RCheesley commented on docs/rest_api/point_triggers.rst
> +     - Name of the User that last modified the point
```suggestion
     - Name of the User that last modified the Point Trigger
```

2023-08-08 18:14 UTC, RCheesley approved these changes

2023-08-08 18:15 UTC, merged