Port over cache doc
mautic/developer-documentation-new pull request #148
Opened 2023-08-17 23:07 UTC by fakela

#59

WIP

2023-08-18 14:36 UTC, RCheesley commented
@fakela I think this is relevant for the current users (Mautic 4). We will need to do another PR for Mautic 5, because the whole system is changing.

When 5.0 General Availability is released we will branch from main -> 4.x and then the current 5.x branch will become main.

2023-08-21 00:00 UTC, fakela commented
@RCheesley I have port over the cache docs that is in the dev documentation. If I am missing out on anything please let me know.


Also once this is confirmed as okay, I'll create another PR using the 5.x branch

2023-08-21 00:01 UTC, fakela commented
I had a little issue previewing this so I stuck to using GitHub preview. I'll try to debug and see how to make it work as expected

2023-08-24 12:48 UTC, RCheesley commented
Should be fixed with Gitpod now - was a problem with the application not being installed I think!

2023-08-30 18:20 UTC, RCheesley requested changes
Quite a lot of updating needed on this PR - it's outdated and there are some Vale fixes.

2023-08-30 18:20 UTC, RCheesley commented on docs/components/cache.rst
> +Symfony makes heavy use of a filesystem cache. Frequently clearing this cache will be required when developing for Mautic. By default, the cache is located in ``app/cache/ENV`` where ``ENV`` is the e
Update for Mautic 3 and beyond (app/console -> bin/console, app/cache -> var/cache) and multiple Vale fixes.

```suggestion
Symfony makes heavy use of a filesystem cache. When developing for Mautic, clearing the cache is a regular occurrence. By default, Mautic instances have the cache located in ``var/cache/ENV`` where ``ENV`` is the environment currently accessed (``dev`` or ``prod``). To rebuild the cache, delete the relevant ``ENV`` folder within the cache directory, or run the Symfony command ``php bin/console cache:clear --env=ENV``. If a specific environment isn't passed to the command via ``--env=ENV``, Mautic uses the ``dev`` environment by default.
```

2023-08-30 18:20 UTC, RCheesley commented on docs/components/cache.rst
> +The typical rule of thumb is, if Mautic is not acting as you expect after making changes, try clearing your cache. If you get "class could not be found" or "cannot redeclare class" errors when using
Update the file path, and Vale fixes.

```suggestion
The typical rule of thumb is, if Mautic isn't acting as you expect after making changes, try clearing your cache. If you get ``class could not be found`` or ``cannot redeclare class`` errors when using the ``cache:clear`` command, manually delete the ``var/cache/ENV`` folder then run the command and/or browse to the site to rebuild.
```

2023-08-30 18:20 UTC, RCheesley commented on docs/components/cache.rst
> +Cache Bundle
```suggestion
Cache bundle
```

2023-08-30 18:20 UTC, RCheesley commented on docs/components/cache.rst
> +Enables PSR-6 and PSR-16 caching. Check: `Symfony Cache Component <https://symfony.com/doc/current/components/cache.html>`_
@fakela please convert this to a link using the 'make link' command within the docs directory, and commit the file that is created. Thanks!

2023-08-30 18:20 UTC, RCheesley commented on docs/components/cache.rst
> +------------
Use the correct heading nesting.
```suggestion
************
```

2023-08-30 18:20 UTC, RCheesley commented on docs/components/cache.rst
> +---------------------
Nesting the headings correctly

```suggestion
====================
```

2023-08-30 18:20 UTC, RCheesley commented on docs/components/cache.rst
> +This bundle introduces tags to cache. All its adapters are fully tag aware which makes the use of namespace obsolete for daily use.
I think this needs a 'the' here but maybe there is a reason why not to. Worth checking with the devs.
```suggestion
This bundle introduces tags to the cache. All its adapters are fully tag aware which makes the use of namespace obsolete for daily use.
```

2023-08-30 18:20 UTC, RCheesley commented on docs/components/cache.rst
> +Previously, if you wanted to keep control on cache section and did not want to hold the index of all keys to clear, you would have to use namespace.
Vale fix
```suggestion
Previously, if you wanted to keep control on cache section and didn't want to hold the index of all keys to clear, you would have to use namespace.
```

2023-08-30 18:20 UTC, RCheesley commented on docs/components/cache.rst
> +Disadvantage of this approach is a new adapter being created for each namespace.
Vale fix
```suggestion
The main disadvantage of this approach is that Mautic creates a new adapter for each namespace.
```

2023-08-30 18:20 UTC, RCheesley commented on docs/components/cache.rst
> +Symfony 3.4 Cache uses tag-aware adapters. If you want to clear all records related to your bundle or component, you just need to tag them.
```suggestion
From Symfony 3.4, the cache uses tag-aware adapters. If you want to clear all records related to your Bundle or Component, you just need to tag them.
```

2023-08-30 18:20 UTC, RCheesley commented on docs/components/cache.rst
> +POOLS CLEARING
```suggestion
Pools clearing
```

2023-08-30 18:20 UTC, RCheesley commented on docs/components/cache.rst
> +Removing Cache Items
```suggestion
Removing cache items
```

2023-08-30 18:20 UTC, RCheesley commented on docs/components/cache.rst
> +Use the ``Psr\\Cache\\CacheItemPoolInterface::deleteItems`` method to delete several cache items simultaneously (it returns true only if all the items have been deleted, even when any or some of them
```suggestion
Use the ``Psr\\Cache\\CacheItemPoolInterface::deleteItems`` method to delete several cache items simultaneously - it returns true only if all the items have been deleted, even when any or some of them don't exist:
```

2023-08-30 18:20 UTC, RCheesley commented on docs/components/cache.rst
> +Plugin comes preconfigured to utilize filesystem caching.
```suggestion
Plugins come preconfigured to utilize filesystem caching.
```

2024-01-09 13:25 UTC, RCheesley commented
@fakela please review feedback here. Thanks!

2024-01-10 21:00 UTC, fakela commented
> @fakela please review feedback here. Thanks!

done

2024-01-11 10:37 UTC, RCheesley commented
This needs to be rebased against 5.x as it was based on main - can you do that @fakela ? Or it might be easier to start a new PR perhaps?

2024-01-15 18:57 UTC, fakela commented
> This needs to be rebased against 5.x as it was based on main - can you do that @fakela ? Or it might be easier to start a new PR perhaps?

I'll create a new PR for it

2024-01-16 21:10 UTC, closed without merging