added 2 new params to email.rst
mautic/developer-documentation-new pull request #150
Opened 2023-08-25 15:56 UTC by Entrepositive

added info for *useOwnerAsMailer* and *utmTags* params to the following:
- Get email response
- Get email properties
- List email response
- Create email properties
- Edit email properties

2023-08-25 16:09 UTC, RCheesley requested changes
Thanks for the PR @Entrepositive 🚀 

A few suggestions based on the Vale feedback - fairly small ones, take a look and see what you think!

2023-08-25 16:09 UTC, RCheesley commented on docs/rest_api/emails.rst
> +     - Array of UTM params, all of which are of type string. Options are: utmSource, utmMedium, utmCampaign, utmContent
This should be the full word:

```suggestion
     - Array of UTM parameters, all of which are of type string. Options are: utmSource, utmMedium, utmCampaign, utmContent
```

2023-08-25 16:09 UTC, RCheesley commented on docs/rest_api/emails.rst
> +     - Whether or not contact owner should be used as mailer. Defaults to TRUE
Fix the Vale warning about Contact being capitalised, and a suggestion for the tense.

```suggestion
     - Should Mautic use the Contact owner as the sender of the Email. Defaults to TRUE
```

2023-08-25 16:09 UTC, RCheesley commented on docs/rest_api/emails.rst
> +     - Array of UTM params, all of which are of type string. Options are: utmSource, utmMedium, utmCampaign, utmContent
As before, use the full word!

```suggestion
     - Array of UTM parameters, all of which are of type string. Options are: utmSource, utmMedium, utmCampaign, utmContent
```

2023-08-25 16:09 UTC, RCheesley commented on docs/rest_api/emails.rst
> +     - Whether or not contact owner should be used as mailer
```suggestion
     - Should Mautic use the Contact owner as the sender of the Email
```

2023-08-25 16:09 UTC, RCheesley commented on docs/rest_api/emails.rst
> +     - Array of UTM params, all of which are of type string. Options are: utmSource, utmMedium, utmCampaign, utmContent
As above!

```suggestion
     - Array of UTM parameters, all of which are of type string. Options are: utmSource, utmMedium, utmCampaign, utmContent
```

2023-08-30 16:54 UTC, RCheesley commented
@all-contributors please add @Entrepositive for docs

2023-08-30 16:55 UTC, merged

2023-08-31 00:27 UTC, Entrepositive commented
Uhoh, sorry for the delay @RCheesley - and thanks for covering me on that.