Amends form validation docs
mautic/developer-documentation-new pull request #181
Opened 2024-02-20 19:24 UTC by putzwasser

Makes slight improvements to the wording in `onValidate`.

Fixes wrong `onValidateEnd` return type description.

@see https://github.com/mautic/mautic/blob/0aaeba2292397926d948d029143a244c9f3f1dc2/app/assets/js/mautic-form-src.js#L485

2024-02-25 05:23 UTC, RCheesley requested changes
Thanks for the PR @putzwasser - quite a few fixes but all for the same thing. We capitalize the name of bundles/components in Mautic which means that Form should be capitalized. Vale seems to have not picked this up, so I will check the settings.

I have also suggested fixes for the failing Vale rules on other areas where active rather than passive voice is required. Hope that helps!

2024-02-25 05:23 UTC, RCheesley commented on docs/components/tracking_script.rst
> +Your callbacks return value determines how the form will be processed:
```suggestion
Your callback's return value determines the processing of the Form:
```

2024-02-25 05:23 UTC, RCheesley commented on docs/components/tracking_script.rst
> +If you wish to run additional code before or after submission of the form, create a ``MauticFormCallback`` object.
```suggestion
If you wish to run additional code before or after submission of the Form, create a ``MauticFormCallback`` object.
```

Please capitalise Form - per the Google StyleGuide definitions we capitalise all the bundles/components of Mautic. Vale should flag these up as a warning.

2024-02-25 05:23 UTC, RCheesley commented on docs/components/tracking_script.rst
> +In the example code, replace ``replaceWithFormName`` with the name of your form.
```suggestion
In the example code, replace ``replaceWithFormName`` with the name of your Form. 
```

2024-02-25 05:23 UTC, RCheesley commented on docs/components/tracking_script.rst
> +Called before built-in form validation.
```suggestion
Called before built-in Form validation.
```

2024-02-25 05:23 UTC, RCheesley commented on docs/components/tracking_script.rst
> +Implement this callback to override the built-in form validation logic.
```suggestion
Implement this callback to override the built-in Form validation logic.
```

2024-02-25 05:23 UTC, RCheesley commented on docs/components/tracking_script.rst
> +1. Return ``True`` to skip the built-in form validation and **continue** with form processing.
```suggestion
1. Return ``True`` to skip the built-in Form validation and **continue** with Form processing.
```

2024-02-25 05:23 UTC, RCheesley commented on docs/components/tracking_script.rst
> +2. Return ``False`` to skip the built-in form validation and **prevent** the form submission.
```suggestion
2. Return ``False`` to skip the built-in Form validation and **prevent** the Form submission.
```

2024-02-25 05:23 UTC, RCheesley commented on docs/components/tracking_script.rst
> +3. Return ``null`` to execute built-in form validation and let its logic determine whether to continue with or prevent the form submission.
```suggestion
3. Return ``null`` to execute built-in Form validation and let its logic determine whether to continue with or prevent the Form submission.
```

2024-02-25 05:23 UTC, RCheesley commented on docs/components/tracking_script.rst
> +Returning ``True`` or ``False`` will skip the execution of `onValidateStart`.
```suggestion
Returning ``True`` or ``False`` skips the execution of `onValidateStart`.
```

2024-02-25 05:23 UTC, RCheesley commented on docs/components/tracking_script.rst
> +           // executed before built-in form validation
```suggestion
           // executed before built-in Form validation
```

2024-02-25 05:23 UTC, RCheesley commented on docs/components/tracking_script.rst
> +Called at the beginning of the default form validation, this receives no values and a return value isn't required and isn't processed.
```suggestion
Called at the beginning of the default Form validation, this receives no values and a return value isn't required and isn't processed.
```

2024-02-25 05:23 UTC, RCheesley commented on docs/components/tracking_script.rst
> +.. warning:: `onValidateStart` will not get executed if you add the ``onValidate`` callback and it returns ``True`` or ``False``.
```suggestion
.. warning:: `onValidateStart` isn't executed if you add the ``onValidate`` callback and it returns ``True`` or ``False``.
```

2024-02-25 05:23 UTC, RCheesley commented on docs/components/tracking_script.rst
> +            // executed before built-in form validation
```suggestion
            // executed before built-in Form validation
```

2024-02-25 05:23 UTC, RCheesley commented on docs/components/tracking_script.rst
> +Called after all form validations are complete - either the default validations and/or the ``onValidate`` callback - and before the form gets submitted.
```suggestion
Called after all Form validations are complete - either the default validations and/or the ``onValidate`` callback - and before submitting the Form.
```

2024-02-25 05:23 UTC, RCheesley commented on docs/components/tracking_script.rst
> +Receives ``formValid`` to determine if the form is valid.
```suggestion
Receives ``formValid`` to determine if the Form is valid.
```

2024-02-25 05:23 UTC, RCheesley commented on docs/components/tracking_script.rst
> +If this callback returns ``False`` then this prevents submitting the form.
```suggestion
If this callback returns ``False`` then this prevents submitting the Form.
```

2024-02-25 05:23 UTC, RCheesley commented on docs/components/tracking_script.rst
> +            // return False; // prevents submitting the form
```suggestion
            // return False; // prevents submitting the Form
```

2024-02-25 05:23 UTC, RCheesley commented on docs/components/tracking_script.rst
> +Called prior to default form submission response processing. Receives ``response`` containing the form submission response.
```suggestion
Called prior to default Form submission response processing. Receives ``response`` containing the Form submission response.
```

2024-02-25 05:23 UTC, RCheesley commented on docs/components/tracking_script.rst
> +Return ``True`` to skip the default form submission response processing.
```suggestion
Return ``True`` to skip the default Form submission response processing.
```

2024-02-25 05:23 UTC, RCheesley commented on docs/components/tracking_script.rst
> +Called at the beginning of the default form submission response processing. Receives ``response`` containing the form submission response.
```suggestion
Called at the beginning of the default Form submission response processing. Receives ``response`` containing the Form submission response.
```

2024-02-25 05:23 UTC, RCheesley commented on docs/components/tracking_script.rst
> +Called at the end default form submission response processing. Receives ``response`` containing the form submission response.
```suggestion
Called at the end of the default Form submission response processing. Receives ``response`` containing the Form submission response.
```

2024-02-25 05:23 UTC, RCheesley commented on docs/components/tracking_script.rst
> +Called prior to going to the next page in the form. Useful to adjust the DOM prior to making the page visible.
```suggestion
Called prior to going to the next page in the Form. Useful to adjust the DOM prior to making the page visible.
```

2024-02-25 05:23 UTC, RCheesley commented on docs/components/tracking_script.rst
> +Called prior to going back to a previous page in the form. Useful to adjust the DOM prior to making the page visible.
```suggestion
Called prior to going back to a previous page in the Form. Useful to adjust the DOM prior to making the page visible.
```

2024-02-25 11:09 UTC, putzwasser commented
Done

2026-01-09 19:40 UTC, adiati98 approved these changes
Thank you for the fixes, @putzwasser! 🚀

2026-01-09 19:42 UTC, merged