Update integrations.rst
mautic/developer-documentation-new pull request #193
Opened 2024-06-15 13:37 UTC by putzwasser

Adds a note on the correct naming of `HelloWorldIntegration::NAME`

2024-06-17 13:35 UTC, RCheesley requested changes
Thanks @putzwasser just a couple of things to tweak.

2024-06-17 13:35 UTC, RCheesley commented on docs/components/integrations.rst
> +    `HelloWorldIntegration::NAME` must only contain letters (a-zA-Z).
```suggestion
   ``HelloWorldIntegration::NAME`` must only contain letters such as a-z or A-Z.
```

Inline code requires double back-ticks for RST, which is why the linter is failing. Also removed the brackets and expanded in text per the prose suggestion.

2024-06-17 18:48 UTC, putzwasser commented
Fixed.

2024-06-18 10:40 UTC, RCheesley approved these changes
Thanks for making the tweaks :)

2026-01-09 19:02 UTC, merged