[UI] Docs explaining how to use the accordion component
mautic/developer-documentation-new pull request #200
Opened 2024-07-18 17:33 UTC by andersonjeccel

This PR introduces documentation for the accordion component, addressing a critical gap in our UI toolkit. Without this, developers would struggle to implement accordions consistently, leading to inconsistent user experiences and increased development time.

Here I provide instructions on how to properly utilize the accordion component, including best practices.

2024-07-24 12:26 UTC, favour-chibueze commented
@RCheesley Could you please help with this issue? I’ve fixed the Vale error, but it seems a link is breaking, which is causing the build to fail.

cc: @andersonjeccel

2024-07-25 15:24 UTC, RCheesley commented
@favour-chibueze it looks like https://docs.mautic.org/en/5.x/configuration/cron_jobs.html#tracking-script is no longer a valid link. This is because it was (rightly) moved out of the Cron Jobs section: https://docs.mautic.org/en/5.x/configuration/tracking_script.html.

So we need a separate PR to fix that build failure in the link file. Can you do that?

2024-07-30 21:05 UTC, favour-chibueze commented
> @favour-chibueze it looks like https://docs.mautic.org/en/5.x/configuration/cron_jobs.html#tracking-script is no longer a valid link. This is because it was (rightly) moved out of the Cron Jobs section: https://docs.mautic.org/en/5.x/configuration/tracking_script.html.
> 
> So we need a separate PR to fix that build failure in the link file. Can you do that?

Here's the [PR](https://github.com/mautic/developer-documentation-new/pull/202) that fixes this

2024-08-14 08:44 UTC, RCheesley commented
Great, good to go then if you're happy with the PR changes @favour-chibueze and they render well. I haven't checked it yet myself.

2024-08-28 17:19 UTC, RCheesley requested changes
I have some concerns about two settings files which I think don't relate to this PR - can you take a look?

2024-08-28 17:19 UTC, RCheesley commented on .vscode/settings.json
I don't think this file should have been committed, should it?

2024-08-28 17:19 UTC, RCheesley commented on .gitpod.yml
Was there a reason to add these extensions?

2024-08-28 17:25 UTC, andersonjeccel commented on .gitpod.yml
I have no idea, they don't appear in changed files here

2024-08-28 17:28 UTC, andersonjeccel commented on .vscode/settings.json
They're not coming from my local instance, as these additions are absent here when I open the file

![image](https://github.com/user-attachments/assets/1e094c61-f7c4-4d68-a9ba-66c93de47c01)

It's probably part of someone's computer (maybe favour's)

2024-08-28 17:30 UTC, andersonjeccel commented on .vscode/settings.json
@RCheesley  Yeah

![image](https://github.com/user-attachments/assets/93d9fdce-cd7a-4770-8ece-437c2f9222ea)

2024-08-28 17:41 UTC, RCheesley commented on .vscode/settings.json
Yeah just saw the same. @favour-chibueze looks like these were committed in error - would you mind making a PR to revert those file commits please? thanks!

2024-08-28 17:53 UTC, andersonjeccel commented on .vscode/settings.json
@RCheesley I reverted, good to go

2024-10-24 16:14 UTC, andersonjeccel commented
@RCheesley It seems RTC

2024-10-24 18:54 UTC, RCheesley commented
Please fix the heading nesting:

```
H1 ###
H2 ***
H3 ===
H4 ---
H5 ~~~
```

2024-11-19 14:24 UTC, RCheesley requested changes
The heading nesting is incorrect in this PR and it needs tweaking before it can be merged. Please see earlier comment.

2025-03-04 09:31 UTC, merged