Add emails REST API doc.
mautic/developer-documentation-new pull request #211
Opened 2024-09-03 13:21 UTC by abhisekmazumdar

PR covers the following:

- Add the Emails REST API documentation.
- Update the documentation to reflect the recent changes made in https://github.com/mautic/mautic/pull/13775

2024-09-03 13:23 UTC, abhisekmazumdar commented
I have tried to the best of my knowledge to convert the Markdown to rst.

I will add any further commits to this PR, which will just have the updates based on https://github.com/mautic/mautic/pull/13775

2024-09-03 17:43 UTC, RCheesley requested changes
Hi @abhisekmazumdar thanks so much for bringing this content over to the developer docs, huge appreciation!

I've made a few comments but there's some things you should tweak for all occurrences and I didn't want to flood the PR with all the recommended changes, so here they are:

When referring to an Email in Mautic, use the capital letter. Only lower case if you're mentioning the act of sending an email or referring to email address, for example.

Please enclose any code snippets or references in either inline code (double backticks) or a code block - in the table each subject should be annotated like this (I've given some examples).

In some cases the content seems to be breaking onto two lines, I don't know how that will render but it's worth looking at whether that has any impact (I haven't built the docs locally to check at this point).

All headings need to be unique, because they generate their URLs and cross-linking snippets from the title. If we can't put that in the actual header - I noticed you're using custom anchors in some places - let's make those anchors relevant to the thing we're describing (e.g. _http-request-get-emails rather than _http-request-1). It makes it much easier for someone reading through the code to know what it's referring to.

It's also helpful to use contractions - don't rather than do not - Vale will pick up more recommendations as you type. If you need help getting set up with Vale in your IDE so that it can hint as you type, let us know - this repo should initialise it for VSCode users with all the plugins, I _think_.

Thanks again for bringing this over, we desperately want to finish this content migration so we can finally close down developer.mautic.org so we really appreciate your help with this!

2024-09-03 17:43 UTC, RCheesley commented on docs/rest_api/emails.rst
> +Use this endpoint to obtain details, create, update or delete Mautic’s
```suggestion
Use this endpoint to obtain details, create, update, or delete Mautic’s
```

Vale fix (oxford comma)

2024-09-03 17:43 UTC, RCheesley commented on docs/rest_api/emails.rst
> +emails.
```suggestion
Emails.
```

2024-09-03 17:43 UTC, RCheesley commented on docs/rest_api/emails.rst
> +Get an individual email by ID.
```suggestion
Get an individual Email by ID.
```

2024-09-03 17:43 UTC, RCheesley commented on docs/rest_api/emails.rst
> +HTTP Request
```suggestion
HTTP request
```

2024-09-03 17:43 UTC, RCheesley commented on docs/rest_api/emails.rst
> +| id           | int          | ID of the email                        |
```suggestion
| id           | int          | ID of the Email                        |
```

2024-09-03 17:43 UTC, RCheesley commented on docs/rest_api/emails.rst
> +| name         | string       | Internal name of the email             |
```suggestion
| name         | string       | Internal name of the Email             |
```

2024-09-03 17:43 UTC, RCheesley commented on docs/rest_api/emails.rst
> +| subject      | stringl      | Subject of the email                   |
```suggestion
| subject      | string      | Subject of the Email                   |
```

I think stringl was a typo?

2024-09-03 17:43 UTC, RCheesley commented on docs/rest_api/emails.rst
> +| fromAddress  | string       | The from email address if it’s         |
```suggestion
| ``fromAddress``  | string       | The from email address if it’s         |
```

2024-09-03 17:43 UTC, RCheesley commented on docs/rest_api/emails.rst
> +| fromName     | string       | The from name if it’s different than   |
```suggestion
| ``fromName``     | string       | The from name if it’s different from   |
```

2024-09-03 17:43 UTC, RCheesley commented on docs/rest_api/emails.rst
> +| plyToAddress |              | different than the one in the Mautic   |
Pop this in double backticks, I don't know why GitHub Is breaking it over two lines.

2024-09-03 17:43 UTC, RCheesley commented on docs/rest_api/emails.rst
> +| bccAddress   | string       | The BCC email address if it’s          |
```suggestion
| ``bccAddress``   | string       | The BCC email address if it’s          |
```

2024-09-03 17:43 UTC, RCheesley commented on docs/rest_api/emails.rst
> +| isPublished  | bool         | Published state                        |
```suggestion
| ``isPublished``  | boolean         | Published state                        |
```

I think it should be the full term, boolean?

2024-09-03 17:43 UTC, RCheesley commented on docs/rest_api/emails.rst
> +| publishUp    | d            | Date/time when the email should be     |
```suggestion
| ``publishUp``    | d            | Date/time when the email should be     |
```

2024-09-03 17:43 UTC, RCheesley commented on docs/rest_api/emails.rst
> +| publishDown  | d            | Date/time the email should be un       |
```suggestion
| ``publishDown``  | d            | Date/time the email should be un       |
```

2024-09-03 17:44 UTC, RCheesley commented on docs/rest_api/emails.rst
> +| publishUp    | d            | Date/time when the email should be     |
Please also check the wording here - we changed all the states from Published to Active or Available, so we might also need to update it here.

2024-09-11 12:15 UTC, abhisekmazumdar commented
I tried to make the suggested changes and also added the `grapesjsbuilder` >> `customMjml` into the tables.
I still see value is complicating few other places. Will try to have a look at it again.

2026-01-09 19:49 UTC, adiati98 commented
@escopecz can you please help review the content here? TIA! ✨

2026-01-12 09:47 UTC, escopecz approved these changes
Looks fine 👍

2026-01-19 18:07 UTC, RCheesley approved these changes
Looks good from my side @adiati98 - all the comments I raised seem to be addressed.

2026-01-19 18:09 UTC, RCheesley requested changes
Just a query on the description terms used - I think it might need to use what's in the UI currently (e.g. Active / Inactive, Available / Unavailable)

2026-01-19 18:09 UTC, RCheesley commented on docs/rest_api/emails.rst
> +| publishUp    | d            | Date/time when the email should be     |
@adiati98 @andersonjeccel I am not sure what we do here - I think the API commands have not changed, but perhaps we should make sure the description aligns with what's now in the UI?

2026-02-23 09:45 UTC, RCheesley approved these changes
GTG Thanks @abhisekmazumdar @adiati98

2026-02-23 09:46 UTC, merged

2026-03-10 09:28 UTC, adiati98 commented
@RCheesley can you please add @abhisekmazumdar to docs at all-contributors? TIA! ✨

2026-04-01 16:24 UTC, RCheesley commented
@all-contributors please add @abhisekmazumdar for docs