[UI] Displaying elements based on user permissions in Twig
mautic/developer-documentation-new pull request #212
Opened 2024-09-09 20:44 UTC by andersonjeccel

This PR shows how to display things conditionally in Twig based on permissions for less-technical people.

@escopecz I'd like your review

2024-09-10 08:11 UTC, escopecz approved these changes
This is correct from the technical review point of view 👍

2024-10-24 12:51 UTC, RCheesley requested changes
Some Vale fixes here - please also can you fix the heading nesting as it's using the wrong syntax.

For reference:

```
H1 ###
H2 ***
H3 ===
H4 ---
H5 ~~~
```

2024-10-24 12:51 UTC, RCheesley commented on docs/design/displaying_elements_based_on_user_permissions.rst
> +Displaying elements based on user permissions
```suggestion
Displaying elements based on User permissions
```

2024-10-24 12:51 UTC, RCheesley commented on docs/design/displaying_elements_based_on_user_permissions.rst
> +In Mautic, it's possible to control the visibility of elements on the user interface based on the user's permissions. This allows for showing or hiding certain features, links, or sections depending
```suggestion
In Mautic, it's possible to control the visibility of elements on the user interface based on the User's permissions. This allows for showing or hiding certain features, links, or sections depending on the User's Role and the permissions associated with that Role.
```

Vale fixes

2024-10-24 12:51 UTC, RCheesley commented on docs/design/displaying_elements_based_on_user_permissions.rst
> +This approach enhances security and provides a tailored experience for each user based on their role and access level.
```suggestion
This approach enhances security and provides a tailored experience for each User based on their role and access level.
```

2024-10-24 12:51 UTC, RCheesley commented on docs/design/displaying_elements_based_on_user_permissions.rst
> +Using the securityIsGranted function
```suggestion
Using the ``securityIsGranted`` function
```

2024-10-24 12:51 UTC, RCheesley commented on docs/design/displaying_elements_based_on_user_permissions.rst
> +To display elements conditionally based on user permissions, use the securityIsGranted function in Twig templates. The securityIsGranted function checks if the current user has the specified permissi
```suggestion
To display elements conditionally based on User permissions, use the ``securityIsGranted`` function in Twig templates. The ``securityIsGranted`` function checks if the current User has the specified permission and returns a boolean value indicating whether the permission is granted or not.
```

2024-10-24 12:51 UTC, RCheesley commented on docs/design/displaying_elements_based_on_user_permissions.rst
> +The 'mautic.user.profile.invite'|trans expression is used to translate the text "Invite your team" using Mautic's translation system. This ensures that the text is displayed in the appropriate langua
```suggestion
The ``'mautic.user.profile.invite'|trans`` expression is used to translate the text 'Invite your team' using Mautic's translation system. This ensures that the text is displayed in the appropriate language based on the user's locale settings.
```

Vale fixes

2024-10-24 12:51 UTC, RCheesley commented on docs/design/displaying_elements_based_on_user_permissions.rst
> +In this structure, 'permission:string' represents the specific permission being checked for. Mautic uses a hierarchical permission system, in the format of 'bundle:level:permission'.
```suggestion
In this structure, ``permission:string`` represents the specific permission being checked for. Mautic uses a hierarchical permission system, in the format of ``bundle:level:permission``.
```

2024-10-24 12:51 UTC, RCheesley commented on docs/design/displaying_elements_based_on_user_permissions.rst
> +Displaying a user invitation link as example
```suggestion
Displaying a User invitation link as example
```

2024-10-24 12:51 UTC, RCheesley commented on docs/design/displaying_elements_based_on_user_permissions.rst
> +Let's examine a practical example of how to use this function to display a link for inviting new users to the platform. This link should only be visible to users who have the permission to create new
```suggestion
  Let's examine a practical example of how to use this function to display a link for inviting new Users to the platform. This link should only be visible to Users who have the permission to create new User accounts.
```

2024-10-24 12:51 UTC, RCheesley commented on docs/design/displaying_elements_based_on_user_permissions.rst
> +In this example, we're using the securityIsGranted function to check if the current user has the 'user:users:create' permission. This permission string is structured to indicate that we're checking f
```suggestion
In this example, we're using the ``securityIsGranted`` function to check if the current User has the ``user:users:create`` permission. This permission string is structured to indicate that we're checking for the ability to create new Users within the User management system.
```

2024-10-24 12:51 UTC, RCheesley commented on docs/design/displaying_elements_based_on_user_permissions.rst
> +If the current user has the user:users:create permission, the code inside the if block will be rendered, displaying the link to invite new users. The link is created using the path function, which ge
```suggestion
If the current User has the ``user:users:create`` permission, the code inside the if block is rendered, displaying the link to invite new users. The path function creates the link, which generates a URL based on the specified route (``mautic_user_action```) and any additional parameters (``{objectAction: 'new'}``).
```

2024-10-24 12:51 UTC, RCheesley commented on docs/design/displaying_elements_based_on_user_permissions.rst
> +[BundleName]/Security/[BundleName]Permissions.php
```suggestion
``[BundleName]/Security/[BundleName]Permissions.php``
```

2024-10-24 12:51 UTC, RCheesley commented on docs/design/displaying_elements_based_on_user_permissions.rst
> +- User permissions: UserBundle/Security/UserPermissions.php
```suggestion
- User permissions: ``UserBundle/Security/UserPermissions.php``
```

2024-10-24 12:51 UTC, RCheesley commented on docs/design/displaying_elements_based_on_user_permissions.rst
> +- Email permissions: EmailBundle/Security/EmailPermissions.php
```suggestion
- Email permissions: ``EmailBundle/Security/EmailPermissions.php``
```

2024-10-24 12:51 UTC, RCheesley commented on docs/design/displaying_elements_based_on_user_permissions.rst
> +- SMS permissions: SmsBundle/Security/SmsPermissions.php
```suggestion
- SMS permissions: ``SmsBundle/Security/SmsPermissions.php``
```

2024-10-24 12:51 UTC, RCheesley commented on docs/design/displaying_elements_based_on_user_permissions.rst
> +These PHP files contain classes that extend AbstractPermissions and define the specific permissions available for that bundle. They usually include methods for building the permission matrix and chec
```suggestion
These PHP files contain classes that extend ``AbstractPermissions`` and define the specific permissions available for that bundle. They usually include methods for building the permission matrix and checking individual permissions.
```

2024-10-24 12:51 UTC, RCheesley commented on docs/design/displaying_elements_based_on_user_permissions.rst
> +- A definePermissions method that outlines all available permissions for the bundle.
```suggestion
- A ``definePermissions`` method that outlines all available permissions for the bundle.
```

2024-10-24 12:51 UTC, RCheesley commented on docs/design/displaying_elements_based_on_user_permissions.rst
> +- Constants defining permission levels (e.g., LEVEL_VIEW, LEVEL_EDIT, LEVEL_FULL).
```suggestion
- Constants defining permission levels (for example, ``LEVEL_VIEW, LEVEL_EDIT, LEVEL_FULL``).
```

2024-10-24 12:51 UTC, RCheesley commented on docs/design/displaying_elements_based_on_user_permissions.rst
> +- Methods for checking specific permissions (e.g., canViewUsers, canEditEmails).
```suggestion
- Methods for checking specific permissions (for example, ``canViewUsers``, ``canEditEmails``).
```

2024-10-24 12:51 UTC, RCheesley commented on docs/design/displaying_elements_based_on_user_permissions.rst
> +For example, in the UserPermissions.php file, the UserPermissions class defines the available permissions for the UserBundle using a more structured approach. Let's go through the important parts:
```suggestion
For example, in the ``UserPermissions.php`` file, the ``UserPermissions`` class defines the available permissions for the ``UserBundle`` using a more structured approach. Let's go through the important parts:
```

2024-10-24 12:51 UTC, RCheesley commented on docs/design/displaying_elements_based_on_user_permissions.rst
> +To use these permission keys with the securityIsGranted function in Twig templates, construct the appropriate permission string. The permission string follows the format: [bundle]:[level]:[permission
```suggestion
To use these permission keys with the ``securityIsGranted`` function in Twig templates, construct the appropriate permission string. The permission string follows the format: ``[bundle]:[level]:[permission]``.
```

2024-10-24 12:51 UTC, RCheesley commented on docs/design/displaying_elements_based_on_user_permissions.rst
> +- editusername => user:profile:editusername
```suggestion
- ``editusername`` => ``user:profile:editusername``
```

2024-10-24 12:51 UTC, RCheesley commented on docs/design/displaying_elements_based_on_user_permissions.rst
> +- editemail => user:profile:editemail
```suggestion
- ``editemail`` => ``user:profile:editemail``
```

2024-10-24 12:51 UTC, RCheesley commented on docs/design/displaying_elements_based_on_user_permissions.rst
> +- editposition => user:profile:editposition
```suggestion
- ``editposition`` => ``user:profile:editposition``
```

2024-10-24 12:51 UTC, RCheesley commented on docs/design/displaying_elements_based_on_user_permissions.rst
> +- editname => user:profile:editname
```suggestion
- ``editname`` => ``user:profile:editname``
```

2024-10-24 12:51 UTC, RCheesley commented on docs/design/displaying_elements_based_on_user_permissions.rst
> +- full => user:profile:full
```suggestion
- ``full`` => ``user:profile:full``
```

2024-10-24 12:51 UTC, RCheesley commented on docs/design/displaying_elements_based_on_user_permissions.rst
> +In each if statement, the securityIsGranted function is used with the corresponding permission string. If the current user has the specified permission, the code inside the if block will be executed,
```suggestion
In each if statement, the ``securityIsGranted`` function is used with the corresponding permission string. If the current user has the specified permission, the code inside the if block will be executed, displaying the relevant form fields for editing the user profile information.
```

2024-10-24 12:51 UTC, RCheesley commented on docs/design/displaying_elements_based_on_user_permissions.rst
> +For more information, refer to the Security documentation.
Can we link to the relevant page/resource here?

2025-03-04 11:51 UTC, merged