Update event_listeners.rst
mautic/developer-documentation-new pull request #220
Opened 2024-10-07 21:57 UTC by ifeoluwafavour

Documentation for Event Listeners component #215

2024-10-08 00:13 UTC, RCheesley requested changes
Thanks so much for the great work on this PR @ifeoluwafavour - it's fantastic to see these docs coming over to the new documentation!

I've left a bunch of suggestions to fix the many Vale suggestions from Reviewdog, have a look and see what you think!

2024-10-08 00:13 UTC, RCheesley commented on docs/plugins/event_listeners.rst
> +Mautic leverages Symfony's EventDispatcher to execute and communicate various actions through Mautic. Plugins can hook into these to extend the functionality of Mautic. Refer to the Extending Mautic
```suggestion
Mautic leverages Symfony's EventDispatcher to execute and communicate various actions through Mautic. Plugins can hook into these to extend the capability of Mautic. Refer to the Extending Mautic section of the documentation for some of the ways to do this.
```
Vale fix

2024-10-08 00:13 UTC, RCheesley commented on docs/plugins/event_listeners.rst
> +The easiest way to listen to various events is to use an event subscriber. Read more about subscribers in `Symfony's documentation<http://symfony.com/doc/current/components/event_dispatcher/introduct
Please use the make link tool at the command line to generate a link file (check there isn't one there already, and please use the similar syntax to the existing link files). Documentation on this feature can be found here: https://sublime-and-sphinx-guide.readthedocs.io/en/latest/references.html#use-the-external-links-extension.

2024-10-08 00:13 UTC, RCheesley commented on docs/plugins/event_listeners.rst
> +Plugin event subscribers can extend ``\Mautic\CoreBundle\EventListener\CommonSubscriber`` which gives access to commonly used dependencies and also allows registering the subscriber service through t
```suggestion
Plugin event subscribers can extend ``\Mautic\CoreBundle\EventListener\CommonSubscriber`` which gives access to commonly used dependencies and also allows registering the subscriber service through the config file for the bundle. See :ref:`plugins/config:Service config items` for more information on registering event services. 
```

Vale fix

2024-10-08 00:13 UTC, RCheesley commented on docs/plugins/event_listeners.rst
> +Available Events
```suggestion
Available events
```

2024-10-08 00:13 UTC, RCheesley commented on docs/plugins/event_listeners.rst
> +There are many events available throughout Mautic. Depending on the desired functionality, look at the core bundle's *Event.php file in the root of the bundle.  For example, Lead related events are d
```suggestion
There are many events available throughout Mautic. Depending on what you're trying to implement, look at the ``*Event.php`` for the core bundle, located in the root of the bundle. For example, the ``app\bundles\LeadBundle\LeadEvents.php`` file defines and describes events relating to Contacts. The final classes provide the names of the events to listen to. Always use the event constants to ensure future changes to event names won't break the Plugin.
```

Vale fixes

2024-10-08 00:13 UTC, RCheesley commented on docs/plugins/event_listeners.rst
> +----------------
```suggestion
----------------

```

2024-10-08 00:13 UTC, RCheesley commented on docs/plugins/event_listeners.rst
> +Custom Events
```suggestion
Custom events
```

2024-10-08 00:13 UTC, RCheesley commented on docs/plugins/event_listeners.rst
> +A plugin can create and dispatch its own events.
```suggestion
A Plugin can create and dispatch its own events. 
```

2024-10-08 00:13 UTC, RCheesley commented on docs/plugins/event_listeners.rst
> +1) The class defining the available events for the plugin using a ``final class`` with constants.
```suggestion
1) The class defining the available events for the Plugin using a ``final class`` with constants.
```

2024-10-08 00:13 UTC, RCheesley commented on docs/plugins/event_listeners.rst
> +2) The Event class that is received by the listeners. This class should extend ``Symfony\Component\EventDispatcher\Event``. It will be created when the event is dispatched and should have any informa
```suggestion
2) The Event class that is received by the listeners. This class should extend ``Symfony\Component\EventDispatcher\Event``. It's created when the event is dispatched and should have any information listeners need to act on it.
```

2024-10-08 09:08 UTC, ifeoluwafavour commented
Hello @RCheesley 
Thank you for your kind words. I'm learning a lot!

I have applied the suggested changes. To accurately follow the external link syntax, I created a pull request to include Symfony's docs event subscribers link file to the link folder:
https://github.com/mautic/developer-documentation-new/pull/221/checks

2024-11-06 19:11 UTC, RCheesley requested changes
Some tweaks to fix the heading nestings, and I've asked the devs to do a technical review, too! Thanks for the great work so far!

2024-11-06 19:11 UTC, RCheesley commented on docs/plugins/event_listeners.rst
>  ===============
```suggestion
###############
```

Please be careful with the heading syntax - it's as follows:

```
H1 ###
H2 ***
H3 ===
H4 ---
H5 ~~~
```

2024-11-06 19:11 UTC, RCheesley commented on docs/plugins/event_listeners.rst
> +-----------
```suggestion
***********
```

Also note: headings must _always_ be unique. This has a high likelihood of breaking that rule. Could you make it more specific to this particular context?

2024-11-06 19:11 UTC, RCheesley commented on docs/plugins/event_listeners.rst
> +----------------
```suggestion
****************
```

2024-11-06 19:11 UTC, RCheesley commented on docs/plugins/event_listeners.rst
> +-------------
```suggestion
*************
```

2024-11-07 08:36 UTC, ifeoluwafavour commented
Thank you @RCheesley for your guidance so far!

I changed 'Subscribers' to 'Event Sunscribers' in the recent commit. Is it a better heading name?

2024-11-19 14:18 UTC, RCheesley requested changes
Looks like just a vale fix and we're good to go! 🚀   Thanks @ifeoluwafavour for all the hard work here!

2024-11-19 14:18 UTC, RCheesley commented on docs/plugins/event_listeners.rst
> +2) The Event class that is received by the listeners. This class should extend ``Symfony\Component\EventDispatcher\Event``. It's created when the event is dispatched and should have any information l
```suggestion
2) The Event class received by the listeners. This class should extend ``Symfony\Component\EventDispatcher\Event``. It's created when dispatching the event and should have any information listeners need to act on it.
```

Vale recommendations

2024-11-19 15:42 UTC, escopecz requested changes

2024-11-19 15:42 UTC, escopecz commented on docs/plugins/event_listeners.rst
> +    // ...
A little bit more modern PHP:
```suggestion
    namespace MauticPlugin\HelloWorldBundle\EventListener;

    use Mautic\LeadBundle\LeadEvent;
    use Mautic\LeadBundle\LeadEvents;
    use Symfony\Component\EventDispatcher\EventSubscriberInterface;

    final class LeadSubscriber extends EventSubscriberInterface
    {
        static public function getSubscribedEvents(): array
        {
            return [
                LeadEvents::LEAD_POST_SAVE     => ['onLeadPostSave', 0],
                LeadEvents::LEAD_POST_DELETE   => ['onLeadDelete', 0],
            ];
        }
    
        public function onLeadPostSave(LeadEvent $event): void
        {
            $lead = $event->getLead();
            
            // do something
        }
    
        public function onLeadDelete(LeadEvent $event): void
        {
            $lead = $event->getLead();
            
            $deletedId = $lead->deletedId;
            
            // do something
        }
    }
    // ...
```

2024-11-19 15:42 UTC, escopecz commented on docs/plugins/event_listeners.rst
> +Plugin event subscribers can extend ``\Mautic\CoreBundle\EventListener\CommonSubscriber`` which gives access to commonly used dependencies and also allows registering the subscriber service through t
```suggestion
Plugin event subscribers can extend ``Symfony\Component\EventDispatcher\EventSubscriberInterface`` which gives access to commonly used dependencies and also allows registering the subscriber service through autowiring.
```

2024-11-19 15:42 UTC, escopecz commented on docs/plugins/event_listeners.rst
> +     */
```suggestion
```
The comment says the same thing as the class itself so it's not necessary

2024-11-19 15:42 UTC, escopecz commented on docs/plugins/event_listeners.rst
> +2) The Event class that is received by the listeners. This class should extend ``Symfony\Component\EventDispatcher\Event``. It's created when the event is dispatched and should have any information l
```suggestion
2) The Event class that is received by the listeners. This class should extend ``Symfony\Contracts\EventDispatcher\Event``. It's created when the event is dispatched and should have any information listeners need to act on it.
```

2024-11-19 15:42 UTC, escopecz commented on docs/plugins/event_listeners.rst
> +    }
Modern PHP with types and updated Symfony namespace for Symfony 5+
```suggestion
    <?php
    // plugins\HelloWorldBundle\Event\ArmageddonEvent.php
    
    namespace MauticPlugin\HelloWorldBundle\Event;
    
    use Symfony\Contracts\EventDispatcher\Event;
    use MauticPlugin\HelloWorldBundle\Entity\World;
    
    final class ArmageddonEvent extends Event
    {
        private bool $falseAlarm = false;
         
        public function __construct(private World $world)
        {
        }
        
        public function shouldPanic(): bool
        {
            return ('earth' == $this->world->getName());
        }
        
        public function setIsFalseAlarm(): void
        {
            $this->falseAlarm = true;
        }
        
        public function getIsFalseAlarm(): bool
        {
            return $this->falseAlarm;
        }
    }
```

2026-01-19 18:25 UTC, RCheesley submitted a review, later dismissed

2026-01-19 18:26 UTC, RCheesley commented
I think this is GTG but we'll need to forward-port it to other branches.

2026-01-25 22:56 UTC, adiati98 commented
> I think this is GTG but we'll need to forward-port it to other branches.

We only have `5.x` branch for this repo at the moment.

2026-02-26 18:17 UTC, RCheesley approved these changes
![Image](https://github.com/user-attachments/assets/a9fc288f-d7b2-4201-be3d-a339e672f9fc)

2026-02-26 18:18 UTC, merged