Update index.rst
mautic/developer-documentation-new pull request #223
Opened 2024-10-22 15:30 UTC by ifeoluwafavour

Resolves #216 - documentation for webhook events and payloads

2024-10-24 12:32 UTC, RCheesley requested changes
Some build errors as the webhook pages aren't on any ToC tree. Please take a look!

2024-10-24 12:32 UTC, RCheesley commented on docs/webhooks/events/index.rst
@ifeoluwafavour when I build the HTML there's a bunch of warnings that these pages do not exist in a ToC tree.

> /Users/rcheesley/Sites/local.newdevdocs/developer-documentation-new/docs/webhooks/events/company_post_delete.rst: WARNING: document isn't included in any toctree
> /Users/rcheesley/Sites/local.newdevdocs/developer-documentation-new/docs/webhooks/events/company_post_save.rst: WARNING: document isn't included in any toctree
> /Users/rcheesley/Sites/local.newdevdocs/developer-documentation-new/docs/webhooks/events/email_on_open.rst: WARNING: document isn't included in any toctree
> /Users/rcheesley/Sites/local.newdevdocs/developer-documentation-new/docs/webhooks/events/email_on_send.rst: WARNING: document isn't included in any toctree
> /Users/rcheesley/Sites/local.newdevdocs/developer-documentation-new/docs/webhooks/events/form_on_submit.rst: WARNING: document isn't included in any toctree
> /Users/rcheesley/Sites/local.newdevdocs/developer-documentation-new/docs/webhooks/events/lead_channel_subscription_changed.rst: WARNING: document isn't included in any toctree
> /Users/rcheesley/Sites/local.newdevdocs/developer-documentation-new/docs/webhooks/events/lead_company_change.rst: WARNING: document isn't included in any toctree
> /Users/rcheesley/Sites/local.newdevdocs/developer-documentation-new/docs/webhooks/events/lead_points_change.rst: WARNING: document isn't included in any toctree
> /Users/rcheesley/Sites/local.newdevdocs/developer-documentation-new/docs/webhooks/events/lead_post_delete.rst: WARNING: document isn't included in any toctree
> /Users/rcheesley/Sites/local.newdevdocs/developer-documentation-new/docs/webhooks/events/lead_post_save_new.rst: WARNING: document isn't included in any toctree
> /Users/rcheesley/Sites/local.newdevdocs/developer-documentation-new/docs/webhooks/events/lead_post_save_update.rst: WARNING: document isn't included in any toctree
> /Users/rcheesley/Sites/local.newdevdocs/developer-documentation-new/docs/webhooks/events/page_on_hit.rst: WARNING: document isn't included in any toctree
> /Users/rcheesley/Sites/local.newdevdocs/developer-documentation-new/docs/webhooks/events/sms_on_send.rst: WARNING: document isn't included in any toctree
> done

Can you please add them, maybe to the root index.rst under the Webhooks section? That way they also come up under the menu when you're clicking through. Thanks!

2024-10-24 13:49 UTC, ifeoluwafavour commented on docs/webhooks/events/index.rst
@RCheesley i have just added the toctree. Is the syntax okay?

2024-11-19 13:49 UTC, RCheesley approved these changes
This looks great @ifeoluwafavour sorry for the delay in getting back to you!

2024-11-19 13:49 UTC, merged