Config form notes interface
mautic/developer-documentation-new pull request #232
Opened 2024-11-19 08:58 UTC by shinde-rahul

2024-12-03 02:59 UTC, shinde-rahul commented on docs/components/integrations.rst
> +The interface, :code:`\Mautic\IntegrationsBundle\Integration\Interfaces\ConfigFormNotesInterface`, provides a way to put notes, either info or warning, on the plugin configuration form.
```suggestion
The interface, :code:`\Mautic\IntegrationsBundle\Integration\Interfaces\ConfigFormNotesInterface`, provides a way to add notes, either info or warning, to the Plugin configuration form.
```

2026-01-10 10:11 UTC, adiati98 requested changes
Hi @shinde-rahul,

Sorry for super late review!

We need some small tweaks here. 🙂 

Also, is this intended for Mautic 5 or 7?

2026-01-10 10:11 UTC, adiati98 commented on docs/components/integrations.rst
> +Config Form Notes Interface
We're using sentence case for titles. So, unless necessary, only the first letter is capitalized.


```suggestion
Config Form notes interface
```

2026-01-10 10:11 UTC, adiati98 commented on docs/components/integrations.rst
> +The interface, :code:`\Mautic\IntegrationsBundle\Integration\Interfaces\ConfigFormNotesInterface`, provides a way to add notes, either info or warning, to the Plugin configuration form.
Let's do dash instead of comma here for readability.


```suggestion
The interface, :code:`\Mautic\IntegrationsBundle\Integration\Interfaces\ConfigFormNotesInterface`, provides a way to add notes - either info or warning - to the Plugin configuration form.
```

2026-01-10 10:11 UTC, adiati98 commented on docs/components/integrations.rst
> +Read more about to how-tos :ref:`Integration Configuration Form Notes<components/integrations_configuration_form_notes:Integration configuration form notes>`
Small tweak here for better read.


```suggestion
Learn more about it on :ref:`Integration Configuration Form Notes<components/integrations_configuration_form_notes:Integration configuration form notes>`.
```

2026-01-10 14:15 UTC, shinde-rahul commented
> Also, is this intended for Mautic 5 or 7?

The code has been there since M5.

2026-01-11 09:36 UTC, adiati98 requested changes
I have a question here and Vale gives new warnings. So, we need to address them.

2026-01-11 09:36 UTC, adiati98 commented on docs/components/integrations.rst
> +The interface, :code:`\Mautic\IntegrationsBundle\Integration\Interfaces\ConfigFormNotesInterface`, provides a way to add notes - either info or warning - to the Plugin configuration form.
**question**: For the code below,

```rst
:code:`\Mautic\IntegrationsBundle\Integration\Interfaces\ConfigFormNotesInterface`
```

Do you want this to render a particular code-block or inline code as the screenshot?

If it's inline code, we can just use double backtick as below:

```rst
``\Mautic\IntegrationsBundle\Integration\Interfaces\ConfigFormNotesInterface``
```

If it's a code block, please use `.. code-block::` and provide the code block.

### Screenshot

<img width="1431" height="317" alt="Image" src="https://github.com/user-attachments/assets/b31fed9d-4161-43e1-9fb0-b7ca340a5dac" />

2026-01-11 09:36 UTC, adiati98 commented on docs/components/integrations.rst
> +Learn more about it on :ref:`Integration Configuration Form Notes<components/integrations_configuration_form_notes:Integration configuration form notes>`.
Vale still gives warning. Let's address this by:

- Fix capitalization in all lines of code, particularly: `Plugin configuration Form` and `Integration configuration Form notes`.

- Wrap these lines in `.. vale off` and `.. vale on` because the other warnings aren't applicable here.


```suggestion
.. vale off

The interface, :code:`\Mautic\IntegrationsBundle\Integration\Interfaces\ConfigFormNotesInterface`, provides a way to add notes - either info or warning - to the Plugin configuration Form.

Learn more about it on :ref:`Integration configuration Form notes<components/integrations_configuration_form_notes:Integration configuration form notes>`.

.. vale on
```

2026-01-19 09:47 UTC, adiati98 approved these changes
Thanks for this, @shinde-rahul! 🚀

2026-01-19 09:47 UTC, merged