[WIP] docs of several components
mautic/developer-documentation-new pull request #26
Opened 2022-03-27 16:40 UTC by dennisameling

2022-04-05 14:03 UTC, dennisameling commented on docs/components/api.rst
>  API
Original docs, please compare: https://developer.mautic.org/#extending-api

2022-04-05 14:05 UTC, dennisameling commented on docs/components/categories.rst
>  Categories
Original docs, please compare: https://developer.mautic.org/#extending-categories

2022-04-05 14:08 UTC, dennisameling commented on docs/components/channels.rst
> +Listening for Channel features
Original docs: https://developer.mautic.org/#extending-broadcasts - please compare

2022-04-05 14:10 UTC, dennisameling commented on docs/components/contacts.rst
> +Contact timeline/history
Original docs: https://developer.mautic.org/#extending-contacts-(leads) - please compare!

2022-04-05 14:11 UTC, dennisameling commented on docs/components/contacts.rst
> +    class LeadSubscriber implements EventSubscriberInterface
Migrated from `CommonSubscriber` (which no longer exists) to EventSubscriberInterface, including proper Dependency Injection

2022-04-05 14:12 UTC, dennisameling commented on docs/components/contacts.rst
> +      - Required - Injects an event into the timeline. Accepts an array with the keys defined as below.
This was in the original docs, but folks can definitely get this from the `LeadTimelineEvent` as well - long-term, I'd actually be in favor of adding this info to the event itself and have auto-generated docs on methods. Should be much less of a maintenance burden then

2022-04-05 14:19 UTC, dennisameling commented on docs/components/emails.rst
>  Emails
This one's big. It removes outdated things that have been removed in Mautic 3 or 4 (like `addTokenSection`). It also adds some new things, like docs on Email Transport/Email providers.

Original docs: https://developer.mautic.org/#extending-emails

2022-04-05 14:27 UTC, dennisameling commented on docs/components/emails.rst
> +            $event->addAbTestWinnerCriteria(
The old docs had a `callback` array key in `addAbTestWinnerCriteria`, but [it was removed in M3](https://github.com/mautic/mautic/pull/8145). Changed it to `event` and added some in-code documentation for it in https://github.com/mautic/mautic/pull/11047

2022-04-05 14:28 UTC, dennisameling commented on docs/components/emails.rst
> +    class MonitoredInboxSubscriber implements EventSubscriberInterface
Replaced `CommonSubscriber` (removed) from the old docs with `EventSubscriberInterface`

2022-04-05 14:30 UTC, dennisameling commented on docs/components/emails.rst
> +This section is in progress. See  ``\Mautic\EmailBundle\Stats\Helper\StatHelperInterface``
Anyone who has experience with email stat helpers? Shall we just leave it out entirely for now? It wasn't in the old docs.

2022-04-05 14:42 UTC, RCheesley requested changes
A few grammatical changes but awesome work, quite the epic PR! 🚀

2022-04-05 14:42 UTC, RCheesley commented on docs/components/categories.rst
> +See a code example in Roles and Permissions (TODO).
TODO here

2022-04-05 14:42 UTC, RCheesley commented on docs/components/emails.rst
> +They get replaced by dynamic content once the Email gets sent or viewed in the browser.
```suggestion
They get replaced by Dynamic Content once the Email gets sent or viewed in the browser.
```

2022-04-05 14:42 UTC, RCheesley commented on docs/components/emails.rst
> +Both leverage the ``\Mautic\EmailBundle\EmailEvents::EMAIL_ON_BUILD`` event. Read more about listeners and subscribers (TODO add link).
TODO here

2022-04-05 14:42 UTC, RCheesley commented on docs/components/emails.rst
> +- ``$event->getContent()`` and ``$event->setContent()`` are used for replacing the email token with actual dynamic content once the Email gets send or viewed in the browser.
```suggestion
- ``$event->getContent()`` and ``$event->setContent()`` are used for replacing the Email token with actual Dynamic Content once the Email gets send or viewed in the browser.
```

2022-04-12 13:35 UTC, escopecz reviewed
Looks great. Thanks Dennis! I have several suggestions for code styles/types to improve the code if someone will be copy-pasting from the examples.

Also, a lot will change in M4. But that's why we'll have versioning in the docs. The sad part is that we'll have to update the docs once again in a few months.

2022-05-04 14:08 UTC, RCheesley requested changes
Awesome work @dennisameling - just a few nitpicks here and there, then it's good to go! 🚀

2022-05-04 14:08 UTC, RCheesley commented on docs/components/api.rst
> +To add custom API endpoints, simply define the routes under the API firewall in the :doc:`Plugin's config file</plugins/config>`.
Don't use the word 'simply' as it makes assumptions :) 

```suggestion
To add custom API endpoints, define the routes under the API firewall in the :doc:`Plugin's config file</plugins/config>`.
```

2022-05-04 14:08 UTC, RCheesley commented on docs/components/categories.rst
> +Please prefix Category keys with ``plugin:`` it determines permissions to manage Categories.
```suggestion
Please prefix Category keys with ``plugin:`` as it determines permissions to manage Categories.
```

2022-05-04 14:08 UTC, RCheesley commented on docs/components/categories.rst
> +There is no need to add custom routes for Categories.
```suggestion
There is no need to add custom routes for Categories,
```

2022-05-04 14:08 UTC, RCheesley commented on docs/components/categories.rst
> +However, when generating a URL to the Plugin's Category list, use the following code:
```suggestion
however, when generating a URL to the Plugin's Category list, use the following code:
```
Suggest bringing this into the same line as the preceding sentence.

2022-05-04 14:08 UTC, RCheesley commented on docs/components/categories.rst
> +Including Category in Forms
```suggestion
Including Categories in Forms
```
If you're referring to singular then 'Including a Category in Forms', but I think we're referring to the plural?

2022-05-04 14:08 UTC, RCheesley commented on docs/components/contacts.rst
> +Using this event, the plugin can inject unique items into the timeline and also into the engagements graph on each page.
```suggestion
Using this event, the Plugin can inject unique items into the timeline and also into the engagements graph on each page.
```

2022-05-23 07:58 UTC, escopecz approved these changes
Thanks Dennis! Looks good to me 👍

2022-05-23 08:50 UTC, merged