Add section about symfony commands
mautic/developer-documentation-new pull request #49
Opened 2022-07-04 15:55 UTC by diaboloshogunate

This is in reference to https://github.com/mautic/mautic/pull/11289/

I am adding a section on Symfony commands rather than documenting the maker command specifically.

I do not think we should document how to use commands we do not maintain.

A cookbook or best practices docs would be the best place to show how to use commands such as the makers command IMO.

2022-07-04 16:47 UTC, RCheesley requested changes
Thanks for the PR @diaboloshogunate - a small grammatical fix I have recommended. We are in the process of re-platforming and updating all of our educational resources following the [Diataxis framework](https://diataxis.fr/) so there will be a home for the more long-form how to guides. 

The dev docs come under '[Reference](https://diataxis.fr/reference/)' so here we would provide the list of the actual commands available specific to Mautic - I think we would not need to list out the existing Doctrine ones, if that was what you meant by commands we don't support?

How they are actually used - for example a walk through of creating a new controller etc - would indeed sit elsewhere. That would most likely be in a development section of the knowledgebase, I expect, and could be linked to from the developer documentation.

You can preview the docs at https://mautic-developer.readthedocs.io/en/latest/ or just use the Gitpod link on your PR and click the files to preview them in the pane on the right, in case that is helpful!

2022-07-04 16:47 UTC, RCheesley commented on docs/plugins/mautic_vs_symfony.rst
> +Mautic includes it's own commands in addition to commands defined by Symfony and Symfony bundles such as the makers bundle.
```suggestion
Mautic includes its own commands in addition to commands defined by Symfony and Symfony bundles such as the makers bundle.
```

2022-07-04 16:54 UTC, diaboloshogunate commented
@RCheesley thanks for catching that. By commands we don't support, I meant ones we do not maintain ourselves such as doctrine, make etc.

2022-07-04 17:05 UTC, RCheesley approved these changes

2022-07-04 17:10 UTC, RCheesley commented
Great - ready to go once the related PR is merged :)

2022-07-27 22:30 UTC, diaboloshogunate commented
@RCheesley https://github.com/mautic/mautic/pull/11313 has been merged

2022-07-28 10:44 UTC, merged

2022-07-28 10:44 UTC, RCheesley commented
Thanks for following up @diaboloshogunate !

2022-07-28 10:44 UTC, RCheesley commented
@all-contributors please add @diaboloshogunate for Docs