Porting Points docs for extending Mautic.
mautic/developer-documentation-new pull request #79
Opened 2022-10-27 10:01 UTC by shinde-rahul

Adding doc for https://github.com/mautic/developer-documentation-new/issues/66

2022-10-27 14:07 UTC, RCheesley requested changes
Just a few small suggestions - great job and good use of the PHP domain!

2022-10-27 14:07 UTC, RCheesley commented on docs/components/points.rst
> +A custom Point Action used to give a Contact `x` Points for doing a certain action.
```suggestion
In Mautic, custom Point Actions give a Contact `x` Points for doing a certain action.
```

2022-10-27 14:07 UTC, RCheesley commented on docs/components/points.rst
> +Mautic dispatches the Event ``\Mautic\PointBundle\PointEvents::POINT_ON_BUILD`` for Plugins to register their custom point action. Listeners receive a ``Mautic\PointBundle\Event\PointBuilderEvent`` o
```suggestion
Mautic dispatches the Event ``\Mautic\PointBundle\PointEvents::POINT_ON_BUILD`` for Plugins to register their custom Point Action. Listeners receive a ``Mautic\PointBundle\Event\PointBuilderEvent`` object. Register the Event using the ``addAction`` method as described below.
```

Let's be consistent with the capitalisation :)

2022-10-27 14:07 UTC, RCheesley commented on docs/components/points.rst
> +Registering a Custom Point Actions
```suggestion
Registering a Custom Point Action
```

2022-10-27 14:07 UTC, RCheesley commented on docs/components/points.rst
> +A custom Point Trigger used to execute a specific action once a Contact hits X number of Points.
```suggestion
A custom Point Trigger used to execute a specific action once a Contact reaches X number of Points.
```

2022-10-27 14:07 UTC, RCheesley commented on docs/components/points.rst
> +Registering a Custom Point Triggers
```suggestion
Registering a Custom Point Trigger
```

2022-11-28 18:54 UTC, dennisameling approved these changes

2022-11-28 18:56 UTC, dennisameling commented
Good to merge from my side. @RCheesley mind doing a final check?

2022-11-28 18:59 UTC, RCheesley requested changes
Just one duplicated colon to fix

2022-11-28 19:02 UTC, dennisameling approved these changes

2022-11-28 20:12 UTC, merged