Porting extending UI doc.
mautic/developer-documentation-new pull request #80
Opened 2022-10-27 10:41 UTC by shinde-rahul

Addressing https://github.com/mautic/developer-documentation-new/issues/72

2022-10-27 14:10 UTC, RCheesley requested changes
Just one small grammar tweak! 🚀

2022-10-27 14:10 UTC, RCheesley commented on docs/components/ui.rst
> +A Plugin can define it's own locations that other Plugins can leverage by using the template ``buttons`` helper.
```suggestion
A Plugin can define its own locations that other Plugins can leverage by using the template ``buttons`` helper.
```

2022-11-27 19:05 UTC, dennisameling approved these changes
This LGTM, thanks @shinde-rahul!

@RCheesley mind doing a final review? Note that Vale reports some suggestions, but it can't show those in the GitHub UI [due to a known issue](https://github.com/errata-ai/vale-action/issues/12) in the Vale action.

https://github.com/mautic/developer-documentation-new/actions/runs/3559535038/jobs/5978951313

2022-11-28 17:30 UTC, dennisameling commented
Update: the Vale checks now run correctly on this PR: https://github.com/mautic/developer-documentation-new/actions/runs/3567127312/jobs/5994433686

@RCheesley want me to address those so we can get this PR merged? 😊

2022-11-28 17:34 UTC, RCheesley commented
Yes please if you have the capacity!

2022-11-28 18:00 UTC, dennisameling approved these changes

2022-11-28 18:01 UTC, dennisameling commented
Done @RCheesley. OK to merge?

2022-11-28 18:03 UTC, RCheesley approved these changes

2022-11-28 18:03 UTC, merged