Add maintenance docs
mautic/developer-documentation-new pull request #94
Opened 2022-12-04 21:07 UTC by dennisameling

Closes #65

Also updated the Code Example as [the current one](https://developer.mautic.org/#extending-maintenance-cleanup) was severely outdated. It used `CommonSubscriber` which has been removed from Mautic a while ago.

2022-12-06 17:41 UTC, RCheesley requested changes
A couple of small suggestions!

2022-12-06 17:41 UTC, RCheesley commented on docs/components/maintenance.rst
> +The event listener should check if data should be deleted or a counted. Use ``$event->setStat($key, $affectedRows, $sql, $sqlParameters)`` to give feedback to the CLI command.
Not sure what you mean by 'a counted' here?

2022-12-06 18:52 UTC, RCheesley commented on docs/components/maintenance.rst
> +.. note:: The Plugin should verify if a dry run got requested using ``$event->isDryRun()`` before deleting records!
Ah OK I can make a better suggestion in that case maybe:

`Use ``$event->isDryRun()`` to verify that a dry run happened before deleting records!`

Would that work?

Appreciate it is hard to figure out sometimes!

2022-12-06 18:53 UTC, RCheesley commented on docs/components/maintenance.rst
> +The event listener should check if data should be deleted or a counted. Use ``$event->setStat($key, $affectedRows, $sql, $sqlParameters)`` to give feedback to the CLI command.
Yeah no problem at all - I didn't understand the English words or what was intended, I guess it meant to say 'or count the number of affected records' perhaps.

2022-12-06 23:31 UTC, dennisameling commented on docs/components/maintenance.rst
> +.. note:: The Plugin should verify if a dry run got requested using ``$event->isDryRun()`` before deleting records!
I just went for this: `Don't delete records when the event is a dry run. You can use ``$event->isDryRun()`` to validate whether this is the case. See the code sample below for more details.` 😊

2022-12-06 23:34 UTC, merged

2022-12-07 08:35 UTC, RCheesley commented on docs/components/maintenance.rst
> +.. note:: The Plugin should verify if a dry run got requested using ``$event->isDryRun()`` before deleting records!
Awesome!