Add Tracking docs
mautic/developer-documentation-new pull request #95
Opened 2022-12-04 22:12 UTC by dennisameling

Closes #71 

As requested in https://github.com/mautic/developer-documentation-new/issues/71, this PR ports all tracking-related docs, both on Contacts and for MauticJS (`mtc.js`):

https://developer.mautic.org/#manipulating-contacts-(leads)
https://developer.mautic.org/#hooking-into-the-tracking-process-and-returning-custom-responses

2022-12-04 22:14 UTC, dennisameling commented on docs/components/contacts.rst
> +  {
The [code block in the old docs](https://developer.mautic.org/#manipulating-contacts-(leads)) was severely outdated and referencing methods that no longer work. The code block below doesn't contain any non-working code, though it does reference some deprecated methods like ``getUniqueIdentiferFields()``. This should be "good enough for now".

2022-12-04 22:15 UTC, dennisameling commented on docs/components/contacts.rst
> +  {
Also refactored this code sample. [Old docs here](https://developer.mautic.org/#manipulating-contacts-(leads)).

2022-12-04 22:16 UTC, dennisameling commented on docs/components/tracking_script.rst
> +You can embed ``mtc.js`` in third party websites to manage communication between those and Mautic.
The only thing I did for the `MauticJS` docs is to port everything over to RST and fix Vale-related errors/warnings/suggestions. I haven't actually tested the code samples, but `MauticJS` doesn't really change a lot so most of it (if not everything) should still work.

2022-12-06 18:03 UTC, RCheesley requested changes
Thanks for the PR @dennisameling - a few suggestions but please do check them for technical validity as I lack the contextual understanding for some of these.

2022-12-06 18:03 UTC, RCheesley commented on docs/components/tracking_script.rst
> +Return value isn't required and not processed.
```suggestion
Return value isn't required and isn't processed.
```

2022-12-06 18:03 UTC, RCheesley commented on docs/components/tracking_script.rst
> +MauticJS API Functions
```suggestion
MauticJS API functions
```

2022-12-06 18:04 UTC, RCheesley commented on docs/components/contacts.rst
> +          // Currently tracked lead based on cookies
While we can't change the references in code, we can update the references in the comments to use the more updated terminology. WDYT?

2022-12-06 23:44 UTC, dennisameling commented on docs/components/tracking_script.rst
> +If you wish execute additional code to execute as the Form is getting processed, create a ``MauticFormCallback`` object.
`being processed` is not allowed by Vale as it's passive voice. Changed it to `If you wish to run additional code before or after submission of the Form, create a ``MauticFormCallback`` object.`

2022-12-06 23:46 UTC, merged

2022-12-07 08:36 UTC, RCheesley commented on docs/components/tracking_script.rst
> +If you wish execute additional code to execute as the Form is getting processed, create a ``MauticFormCallback`` object.
Ahh, lesson to review PRs within the environment to check for the Vale errors! Thanks!